### PR TITLE
Some minor fixes

### PR DESCRIPTION
**Pull request by darkchylde**
@alfredfrancis Some minor fixes here and there. Something I have noticed through the source code is that variable naming convention isn't compatible with PEP-8. Is it a convention to use lowerCamelCase for naming variable for this project ? 

Regarding unit tests, should all the unit tests be grouped together in the tests folder or should the blueprint unit tests be grouped in to tests folder in the respective blueprints ?

### CODE REVIEW

**Comment by alfredfrancis** [comment]
We just began with lowerCamelCase but we'd like to have PEP-8 conventions in place and also the unit tests. I think its better group the unit tests to be grouped in the tests folder. Looking forward to your contributions.

**Comment by darkchylde** [comment]
Sure.

**Comment by darkchylde** [comment]
I hope you have documentation in mind. Since the project is getting popular, people would like to chip in, so I think it would be better to have standard documentation for api routes and the source code. If you are planning to buy a domain and space, host the project there with documentation, please let me know, I would like to chip in as well.

I am sorry, this thread ain't the right place for this discussion. Hope you will setup an IRC chatroom or telegram group for the same. Or is gitter the standard way of communication ?

PS: Great work with the project. Good to contribute to it on my own way.

**Comment by alfredfrancis** [comment]
This was started as a hobby project. I didn't get to put in best practices.Now that lots of people started using this, I'm preparing a new roadmap for the project. Let's discuss more on Gitter and take it further.

**Comment by hydercps** [comment]
I can not agree more. More documents need to be added. This is a good project, definitely.

**Pull request merged**
